### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by NPG-Soul** [JonBons/Sublime-SQF-Language#14]
The following 2 commands are missing for Arma 2 scripting.
Keep in mind these 2 do NOT exist in Arma 3.

setVehicleInit
processInitCommands

**Comment by Jamesadamar** [comment]
hm hard to decide whether to add them, my feelings are to let them out, no further need as you mentioned and not so many ArmA2 mission makers and scripters left, are there?

**Comment by Ragebone** [comment]
Arma 3 Try / Catch is incomplete.
highlight of _exception and the completion of the structure isn't there.
http://killzonekid.com/arma-scripting-tutorials-exception-handling-try-throw-catch/

i will try to figure out how to add it.

**Comment by Jamesadamar** [comment]
will look into this
