### ISSUE TITLE
Check all latest ArmA3 Updates and missing commands

### ISSUE THREAD

**Issue by Jamesadamar** [JonBons/Sublime-SQF-Language#21]
https://community.bistudio.com/wiki/Category:Scripting_Commands_Arma_3

**Comment by commy2** [comment]
Note that some of the commands on that wiki are written wrong. E.g. `diag_log` vs. `diag log`

Full list:
https://gist.github.com/commy2/f2496af4bccb256ec879af301ccdae35

**Comment by commy2** [comment]
Can be closed after https://github.com/JonBons/Sublime-SQF-Language/pull/23 I think.
