### ISSUE TITLE
Synxtax coloring

### ISSUE THREAD

**Issue by StokesMagee** [JonBons/Sublime-SQF-Language#24]
There seems to be a coloring issue with comments.
( /* comment */ )
and 
( // comment)

![image](https://cloud.githubusercontent.com/assets/16112129/17274030/cef76faa-569a-11e6-82d2-2bd6986cfe59.png)

**Comment by KamikazeXeX** [comment]
Can confirm this is also a issue for myself
![image](https://cloud.githubusercontent.com/assets/8187242/17274034/e94573f0-56c4-11e6-8441-8bb12870730f.png)

**Comment by StokesMagee** [comment]
Issue appears to be related to https://github.com/JonBons/Sublime-SQF-Language/commit/8de744faf035d6b820ffcceb60a5c41f1c58feb9

**Comment by commy2** [comment]
I get it. It's a side effect of making `/` a math command. Should be fixed by changing the order of math commands vs comments

**Comment by KamikazeXeX** [comment]
Changing the order to prioritize comments while preserving / as math seems to work for me, thanks.

**Comment by StokesMagee** [comment]
:(
![image](https://cloud.githubusercontent.com/assets/16112129/17283041/383e9530-577a-11e6-8e21-cc80dfe09742.png)

**Comment by KamikazeXeX** [comment]
It would appear that the & operator syntax is also affected, so far haven't attempted to restore old behaviour as its a small issue but it would be nice to also get this resolved (I'm big on syntax styles)
![image](https://cloud.githubusercontent.com/assets/8187242/17283043/24c2f274-57a4-11e6-969d-a01f67251696.png)

**Comment by commy2** [comment]
I fixed this in https://github.com/JonBons/Sublime-SQF-Language/pull/27
Sorry that I didn't notice that you can't use escaping inside `\b()`
